modLoader="javafml" 
loaderVersion="[43,)"
license="MIT"

[[mods]]
modId="minetime"
version="1.0"
displayName="MineTimeMod"
description='''
TimerMod for Minecraft 1.19.2
'''
authors="Puxpui"
# Add this line to indicate the mod has a client-side configuration
clientConfig="com.example.examplemod.Config"
